
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          # - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: t_openai_models 
    description: "the openai model list"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: t_ollama_models 
    description: "the embedding model list"
    columns:
      - name: name
        tests:
          - unique
          - not_null
